config:
  import_variables:
  - variables/dynamic.yaml
  - variables/general.yaml
  - variables/colours.yaml
  backup: true
  banner: true
  create: true
  dotpath: files
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_marimo:
    dst: ~/.marimo.toml
    src: marimo.toml
  f_travis:
    dst: ~/.travis.conf
    src: travis.conf
  f_starship:
    dst: ~/.config/starship.toml
    src: starship.toml
  d_helix:
    dst: ~/.config/helix
    src: helix
    cmpignore:
    - runtime
  d_mise:
    dst: ~/.config/mise
    src: mise
  d_fish:
    dst: ~/.config/fish
    src: fish
  d_i3:
    dst: ~/.config/i3
    src: i3
  d_polybar:
    dst: ~/.config/polybar
    src: polybar
  d_rofi:
    dst: ~/.config/rofi
    src: rofi
  d_kitty:
    dst: ~/.config/kitty
    src: kitty
  f_git:
    dst: ~/.gitconfig
    src: gitconfig
  d_gh:
    dst: ~/.config/gh
    src: gh
    cmpignore:
    - hosts.yml
  d_picom:
    dst: ~/.config/picom
    src: picom
  d_nvim:
    dst: ~/.config/nvim
    src: nvim
profiles:
  macos:
    variables:
      devicename: macos
    dotfiles:
    - f_marimo
    - f_travis
    - f_starship
    - d_helix
    - d_mise
    - d_fish
    - d_kitty
    - f_git
    - d_nvim
  ubuntu:
    variables:
      devicename: ubuntu
    dotfiles:
    - f_marimo
    - f_travis
    - f_starship
    - d_helix
    - d_mise
    - d_fish
    - d_kitty
    - f_git
    - d_i3
    - d_polybar
    - d_rofi
    - d_gh
    - d_picom
    - d_nvim
