config:
  import_variables:
    - variables/dynamic.yaml
    - variables/general.yaml
    - variables/colours.yaml
  backup: true
  banner: true
  create: true
  dotpath: files
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_marimo:
    dst: ~/.marimo.toml
    src: marimo.toml
  f_travis:
    dst: ~/.travis.conf
    src: travis.conf
  f_starship:
    dst: ~/.config/starship.toml
    src: starship.toml
  d_helix:
    dst: ~/.config/helix
    src: helix  
    cmpignore: 
      - 'runtime'
  d_mise:
    dst: ~/.config/mise
    src: mise
  d_fish:
    dst: ~/.config/fish
    src: fish
  d_i3:
    dst: ~/.config/i3
    src: i3
  d_polybar:
    dst: ~/.config/polybar
    src: polybar
  d_rofi:
    dst: ~/.config/rofi
    src: rofi
  d_kitty:
    dst: ~/.config/kitty
    src: kitty
profiles:
  mbair:
    variables:
      devicename: "mbair"      
    dotfiles:
      - f_marimo
      - f_travis
      - f_starship
      - d_helix
      - d_mise
      - d_fish
      - d_kitty
  nipogi:
    variables:
      devicename: "nipogi"      
    dotfiles:
      - f_marimo
      - f_travis
      - f_starship
      - d_helix
      - d_mise
      - d_fish
      - d_kitty
      - d_i3
      - d_polybar
      - d_rofi
